apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 13378
      protocol: TCP
      targetPort: 80
  selector:
    app: audiobookshelf
  externalIPs:
  - 192.168.0.211
  - 192.168.0.221
  - 192.168.0.222
  - 192.168.0.223
  - 192.168.0.224
